export const mockProducts = [
  {
    id: 1,
    name: "Nước giặt cho da nhạy cảm - Econova Bucato White Inpoallegenico",
    price: 300000,
    discount: 50,
    sold: 28400,
    image: "/images/product-1.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 2,
    name: "Quạt Turbo cầm tay Mini siêu mạnh - 5000mAH - 3 tốc độ gió",
    price: 12990000,
    discount: 0,
    sold: 13500,
    image: "/images/product-2.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 3,
    name: "Nước súc miệng dịu nhẹ Garglin dành cho người lớn chai 750ml",
    price: 189000,
    discount: 7,
    sold: 7300,
    image: "/images/product-3.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 4,
    name: "Sách IELTS 4 Kỹ Năng",
    price: 399000,
    discount: 30,
    sold: 987,
    image: "/images/product-4.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 5,
    name: "Loop Quiet 2 - Nút tai giảm tiếng ồn (-24dB) để ngủ, tập trung, học tập, nhạy tiếng ồn & du lịch - Bảo vệ thính lực siêu mềm, có thể tái sử dụng",
    price: 550000,
    discount: 10,
    sold: 4300,
    image: "/images/product-5.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 6,
    name: "[Ghế Roichen] Ghế chỉnh dáng Roichen nhập khẩu Hàn Quốc (Made in Korea) dành cho Nam, Nữ, trẻ em",
    price: 660000,
    discount: 0,
    sold: 3500,
    image: "/images/product-6.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 7,
    name: "Điện thoại Xiaomi 14T14T 12GB/256GB Chính hãng",
    price: 11890000,
    discount: 55,
    sold: 22300,
    image: "/images/product-7.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 8,
    name: "Kem Chấm Mụn Giảm Sưng Viêm, Mờ Thâm Sẹo Sau 48h Thế Hệ Mới Decumar ProMax Cream 15g",
    price: 185000,
    discount: 5,
    sold: 19500,
    image: "/images/product-8.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 9,
    name: "Nước giặt cho da nhạy cảm - Econova Bucato White Inpoallegenico",
    price: 300000,
    discount: 50,
    sold: 28400,
    image: "/images/product-1.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 10,
    name: "Quạt Turbo cầm tay Mini siêu mạnh - 5000mAH - 3 tốc độ gió",
    price: 12990000,
    discount: 0,
    sold: 13500,
    image: "/images/product-2.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 11,
    name: "Nước súc miệng dịu nhẹ Garglin dành cho người lớn chai 750ml",
    price: 189000,
    discount: 7,
    sold: 7300,
    image: "/images/product-3.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 12,
    name: "Sách IELTS 4 Kỹ Năng",
    price: 399000,
    discount: 30,
    sold: 987,
    image: "/images/product-4.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 13,
    name: "Loop Quiet 2 - Nút tai giảm tiếng ồn (-24dB) để ngủ, tập trung, học tập, nhạy tiếng ồn & du lịch - Bảo vệ thính lực siêu mềm, có thể tái sử dụng",
    price: 550000,
    discount: 10,
    sold: 4300,
    image: "/images/product-5.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 14,
    name: "[Ghế Roichen] Ghế chỉnh dáng Roichen nhập khẩu Hàn Quốc (Made in Korea) dành cho Nam, Nữ, trẻ em",
    price: 660000,
    discount: 0,
    sold: 3500,
    image: "/images/product-6.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 15,
    name: "Điện thoại Xiaomi 14T14T 12GB/256GB Chính hãng",
    price: 11890000,
    discount: 55,
    sold: 22300,
    image: "/images/product-7.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 16,
    name: "Kem Chấm Mụn Giảm Sưng Viêm, Mờ Thâm Sẹo Sau 48h Thế Hệ Mới Decumar ProMax Cream 15g",
    price: 185000,
    discount: 5,
    sold: 19500,
    image: "/images/product-8.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 17,
    name: "Nước giặt cho da nhạy cảm - Econova Bucato White Inpoallegenico",
    price: 300000,
    discount: 50,
    sold: 28400,
    image: "/images/product-1.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 18,
    name: "Quạt Turbo cầm tay Mini siêu mạnh - 5000mAH - 3 tốc độ gió",
    price: 12990000,
    discount: 0,
    sold: 13500,
    image: "/images/product-2.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 19,
    name: "Nước súc miệng dịu nhẹ Garglin dành cho người lớn chai 750ml",
    price: 189000,
    discount: 7,
    sold: 7300,
    image: "/images/product-3.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 20,
    name: "Sách IELTS 4 Kỹ Năng",
    price: 399000,
    discount: 30,
    sold: 987,
    image: "/images/product-4.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 21,
    name: "Loop Quiet 2 - Nút tai giảm tiếng ồn (-24dB) để ngủ, tập trung, học tập, nhạy tiếng ồn & du lịch - Bảo vệ thính lực siêu mềm, có thể tái sử dụng",
    price: 550000,
    discount: 10,
    sold: 4300,
    image: "/images/product-5.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 22,
    name: "[Ghế Roichen] Ghế chỉnh dáng Roichen nhập khẩu Hàn Quốc (Made in Korea) dành cho Nam, Nữ, trẻ em",
    price: 660000,
    discount: 0,
    sold: 3500,
    image: "/images/product-6.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 23,
    name: "Điện thoại Xiaomi 14T14T 12GB/256GB Chính hãng",
    price: 11890000,
    discount: 55,
    sold: 22300,
    image: "/images/product-7.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 24,
    name: "Kem Chấm Mụn Giảm Sưng Viêm, Mờ Thâm Sẹo Sau 48h Thế Hệ Mới Decumar ProMax Cream 15g",
    price: 185000,
    discount: 5,
    sold: 19500,
    image: "/images/product-8.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
  {
    id: 25,
    name: "Nước giặt cho da nhạy cảm - Econova Bucato White Inpoallegenico",
    price: 300000,
    discount: 50,
    sold: 28400,
    image: "/images/product-1.png",
    freeShipping: true,
    gift: true,
    flashSale: true,
  },
  {
    id: 26,
    name: "Quạt Turbo cầm tay Mini siêu mạnh - 5000mAH - 3 tốc độ gió",
    price: 12990000,
    discount: 0,
    sold: 13500,
    image: "/images/product-2.png",
    freeShipping: true,
    gift: false,
    flashSale: false,
  },
  {
    id: 27,
    name: "Nước súc miệng dịu nhẹ Garglin dành cho người lớn chai 750ml",
    price: 189000,
    discount: 7,
    sold: 7300,
    image: "/images/product-3.png",
    freeShipping: false,
    gift: true,
    flashSale: true,
  },

  {
    id: 28,
    name: "Sách IELTS 4 Kỹ Năng",
    price: 399000,
    discount: 30,
    sold: 987,
    image: "/images/product-4.png",
    freeShipping: false,
    gift: false,
    flashSale: true,
  },
];
